//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARealmRepopulated.Data.l10n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArrpContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArrpContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARealmRepopulated.Data.l10n.ArrpContent", typeof(ArrpContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Configuration.
        /// </summary>
        public static string ListWnd_Close {
            get {
                return ResourceManager.GetString("ListWnd_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically loads available scenarios on start. Also keeps track of the file status and reloads if changes to the files are detected..
        /// </summary>
        public static string ListWnd_Options_AutoLoad_Desc {
            get {
                return ResourceManager.GetString("ListWnd_Options_AutoLoad_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto load scenarios.
        /// </summary>
        public static string ListWnd_Options_AutoLoad_Option {
            get {
                return ResourceManager.GetString("ListWnd_Options_AutoLoad_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debug overlay is used to display the scenario actor paths when editing a specific scenario. To give an example: Without it you dont have access to the drag and drop functionallities for movement nodes.\nYou can disable this option if you not plan on editing the scenarios..
        /// </summary>
        public static string ListWnd_Options_DebugOverlay_Desc {
            get {
                return ResourceManager.GetString("ListWnd_Options_DebugOverlay_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable debug overlay.
        /// </summary>
        public static string ListWnd_Options_DebugOverlay_Option {
            get {
                return ResourceManager.GetString("ListWnd_Options_DebugOverlay_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a clickable entry in the DTR bar. It provides quick access to the configuration menu and displays the count of loaded scenarios in the current area..
        /// </summary>
        public static string ListWnd_Options_DtrBar_Desc {
            get {
                return ResourceManager.GetString("ListWnd_Options_DtrBar_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show DTR Entry.
        /// </summary>
        public static string ListWnd_Options_DtrBar_Option {
            get {
                return ResourceManager.GetString("ListWnd_Options_DtrBar_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string ListWnd_Options_Title {
            get {
                return ResourceManager.GetString("ListWnd_Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new scenario.
        /// </summary>
        public static string ListWnd_Scenario_Action_Add_Desc {
            get {
                return ResourceManager.GetString("ListWnd_Scenario_Action_Add_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this scenario.
        /// </summary>
        public static string ListWnd_Scenario_Action_DeleteScenario_Desc {
            get {
                return ResourceManager.GetString("ListWnd_Scenario_Action_DeleteScenario_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this scenario.
        /// </summary>
        public static string ListWnd_Scenario_Action_EditScenario_Desc {
            get {
                return ResourceManager.GetString("ListWnd_Scenario_Action_EditScenario_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the scenario file folder.
        /// </summary>
        public static string ListWnd_Scenario_Action_OpenFolder_Desc {
            get {
                return ResourceManager.GetString("ListWnd_Scenario_Action_OpenFolder_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan the available scenario files.
        /// </summary>
        public static string ListWnd_Scenario_Action_Scan_Desc {
            get {
                return ResourceManager.GetString("ListWnd_Scenario_Action_Scan_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your custom scenarios in this section. You can create, edit and delete scenarios as you like. Please be aware that having too many scenarios and actors at the same time in the same location might impact performance. The scenarios are stored as files in the &apos;scenarios&apos; subfolder located in the plugin configuration directory..
        /// </summary>
        public static string ListWnd_Scenario_Desc {
            get {
                return ResourceManager.GetString("ListWnd_Scenario_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ListWnd_Scenario_Popup_DeleteScenario_Accept {
            get {
                return ResourceManager.GetString("ListWnd_Scenario_Popup_DeleteScenario_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ListWnd_Scenario_Popup_DeleteScenario_Decline {
            get {
                return ResourceManager.GetString("ListWnd_Scenario_Popup_DeleteScenario_Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the scenario &apos;{0}&apos;.
        /// </summary>
        public static string ListWnd_Scenario_Popup_DeleteScenario_Desc {
            get {
                return ResourceManager.GetString("ListWnd_Scenario_Popup_DeleteScenario_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ListWnd_Scenario_Popup_DeleteScenario_Title {
            get {
                return ResourceManager.GetString("ListWnd_Scenario_Popup_DeleteScenario_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search ... .
        /// </summary>
        public static string ListWnd_Scenario_Search_Placeholder {
            get {
                return ResourceManager.GetString("ListWnd_Scenario_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        public static string ListWnd_Scenario_Title {
            get {
                return ResourceManager.GetString("ListWnd_Scenario_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARealmRepopulated Configuration.
        /// </summary>
        public static string ListWnd_Title {
            get {
                return ResourceManager.GetString("ListWnd_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Introduction.
        /// </summary>
        public static string OnboardingWnd_Close {
            get {
                return ResourceManager.GetString("OnboardingWnd_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Realm Repopulated - Welcome !.
        /// </summary>
        public static string OnboardingWnd_Header {
            get {
                return ResourceManager.GetString("OnboardingWnd_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the onboarding wizzard for the plugin &apos;A Realm Repopulated&apos;. The purpose of it is to give you the ability to enhance your surroundings by adding additional background NPCs. Each NPC can be given a set of instructions that guides its behaviour to create the feeling of the world being a bit more alive then usual..
        /// </summary>
        public static string OnboardingWnd_Intro {
            get {
                return ResourceManager.GetString("OnboardingWnd_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thats it for now. Play around a bit and tell me what you think. Have fun!.
        /// </summary>
        public static string OnboardingWnd_Outro {
            get {
                return ResourceManager.GetString("OnboardingWnd_Outro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo scenario created by the onboarding wizzard..
        /// </summary>
        public static string OnboardingWnd_Scenario_Desc {
            get {
                return ResourceManager.GetString("OnboardingWnd_Scenario_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can edit my actions via the configuration window. Try opening it by typing /arrp!.
        /// </summary>
        public static string OnboardingWnd_Scenario_Npc_Explain1 {
            get {
                return ResourceManager.GetString("OnboardingWnd_Scenario_Npc_Explain1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will take my leave now, but if you wait for a few seconds i will reappear here!.
        /// </summary>
        public static string OnboardingWnd_Scenario_Npc_Explain2 {
            get {
                return ResourceManager.GetString("OnboardingWnd_Scenario_Npc_Explain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello !!.
        /// </summary>
        public static string OnboardingWnd_Scenario_Npc_Greeting {
            get {
                return ResourceManager.GetString("OnboardingWnd_Scenario_Npc_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My name is {0}. I am here to bid you welcome..
        /// </summary>
        public static string OnboardingWnd_Scenario_Npc_Intro {
            get {
                return ResourceManager.GetString("OnboardingWnd_Scenario_Npc_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have fun!.
        /// </summary>
        public static string OnboardingWnd_Scenario_Npc_Outro {
            get {
                return ResourceManager.GetString("OnboardingWnd_Scenario_Npc_Outro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction to scenarios.
        /// </summary>
        public static string OnboardingWnd_Scenario_Title {
            get {
                return ResourceManager.GetString("OnboardingWnd_Scenario_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Settings.
        /// </summary>
        public static string OnboardingWnd_Settings {
            get {
                return ResourceManager.GetString("OnboardingWnd_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interactions are grouped in a container called &apos;Scenario&apos; and each scenario is bound to a location. You can view them in the plugins settings.
        /// </summary>
        public static string OnboardingWnd_SettingsDesc {
            get {
                return ResourceManager.GetString("OnboardingWnd_SettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn Demo NPC.
        /// </summary>
        public static string OnboardingWnd_Spawn {
            get {
                return ResourceManager.GetString("OnboardingWnd_Spawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see how it works, you can use the button below to spawn a dummy NPC to see the plugin working..
        /// </summary>
        public static string OnboardingWnd_SpawnDesc {
            get {
                return ResourceManager.GetString("OnboardingWnd_SpawnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario created.
        /// </summary>
        public static string OnboardingWnd_SpawnSuccess {
            get {
                return ResourceManager.GetString("OnboardingWnd_SpawnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Start.
        /// </summary>
        public static string OnboardingWnd_Title {
            get {
                return ResourceManager.GetString("OnboardingWnd_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despawnes the actor. This does not unload it but disables the drawing cycles..
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_ADespawn_Desc {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_ADespawn_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despawn.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_ADespawn_Short {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_ADespawn_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_ADuration_Short {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_ADuration_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plays an emote. If the emote supports looping and no timelimit is specified, it continues to do so..
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_AEmote_Desc {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_AEmote_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop emote for duration.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_AEmote_Loop {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_AEmote_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_AEmote_Select {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_AEmote_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Emote.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_AEmote_SelectHint {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_AEmote_SelectHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_AEmote_Short {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_AEmote_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay in emote pose after end.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_AEmote_StayInPos {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_AEmote_StayInPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the actor to the idle state..
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_AIdle_Desc {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_AIdle_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_AIdle_Short {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_AIdle_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walks, or runs, the actor to a specific location. If the target is at a different angle than the actor is looking at, this action rotates the actor first in the correct direction..
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_AMove_Desc {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_AMove_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_AMove_Position {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_AMove_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to current location.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_AMove_Position_CurrentLocationHint {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_AMove_Position_CurrentLocationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_AMove_Short {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_AMove_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_AMove_Speed {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_AMove_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Point.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_APath_AddPoint {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_APath_AddPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new point to the collection. If one was previously selected in the list, the new point is inserted below your selection..
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_APath_AddPointHint {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_APath_AddPointHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a path based on a point lists. The actor walks or runs along this path more naturally as opposed to multiple move actions..
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_APath_Desc {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_APath_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to current location.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_APath_Position_CurrentLocationHint {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_APath_Position_CurrentLocationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this point from the collection.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_APath_RemovePointHint {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_APath_RemovePointHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this point as active for display in the debugger. Also determines the insert point for new points..
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_APath_SelectPointHint {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_APath_SelectPointHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_APath_Short {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_APath_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tension.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_APath_Tension {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_APath_Tension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines how &apos;curvy&apos; the npc will move along the path. A value of 0 equals drunk, a value of 1 means thunder. A value between 0.25 and 0.5 yields a natural response in normal circumstances..
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_APath_TensionHint {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_APath_TensionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotates the actor to a given angle..
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_ARotation_Desc {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_ARotation_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Current Rotation.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_ARotation_SetCurrent {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_ARotation_SetCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_ARotation_Short {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_ARotation_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn the actor in if it was previously despawned..
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_ASpawn_Desc {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_ASpawn_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_ASpawn_Short {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_ASpawn_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauses continuation of the action list until every scenario actor has reached the same sync action.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_ASync_Desc {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_ASync_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_ASync_Short {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_ASync_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Npc Talk.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_ATalk_Short {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_ATalk_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simply waits at the current location for a specific time..
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_AWaiting_Desc {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_AWaiting_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_AWaiting_Short {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_AWaiting_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_Title {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_WalkSpeed_Running {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_WalkSpeed_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking.
        /// </summary>
        public static string ScenarioEditor_ActorData_Actions_WalkSpeed_Walking {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Actions_WalkSpeed_Walking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base ID.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CBase {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bust size.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CBustSize {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CBustSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyebrows.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CEyebrows {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CEyebrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Color Left.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CEyeColorLeft {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CEyeColorLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Color Right.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CEyeColorRight {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CEyeColorRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Shape.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CEyeShape {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CEyeShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CFace {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facial Features.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CFacialFeatures {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CFacialFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facial Features Color.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CFacialFeaturesColor {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CFacialFeaturesColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CGender {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haircolor.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CHairColor {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CHairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairstyle.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CHairstyle {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CHairstyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Headgear.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CHeadgearHidden {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CHeadgearHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CHeight {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CHighlights {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CHighlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights Color.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CHighlightsColor {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CHighlightsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaw.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CJaw {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CJaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lip Color / Fur Pattern.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CLipColorFurPattern {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CLipColorFurPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lipstick.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CLipstick {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CLipstick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MuscleMass.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CMuscleMass {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CMuscleMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nose.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CNose {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CNose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CRace {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Skeleton ID.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CSkeleton {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CSkeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkinColor.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CSkinColor {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CSkinColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tail shape.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CTailShape {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CTailShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribe.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CTribe {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CTribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Weapons.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_CWeaponsHidden {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_CWeaponsHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC Appearance can be changed by choosing a template from your environment. It is currently not planned to include a character editor..
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_Desc {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_EBody {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_EBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earings.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_EEars {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_EEars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_EFeet {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_EFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glasses.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_EGlasses {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_EGlasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_EHands {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_EHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headgear.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_EHeadgear {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_EHeadgear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_ELegs {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_ELegs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mainhand.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_EMainHand {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_EMainHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necklace.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_ENeck {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_ENeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offhand.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_EOffHand {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_EOffHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC Equipment.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_Equip {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_Equip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring (left).
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_ERingLeft {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_ERingLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring (right).
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_ERingRight {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_ERingRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armband.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_EWrist {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_EWrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC Model.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_Model {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_Setup {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the appearance of the npc from an existing source..
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_Setup_Desc {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_Setup_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from clipboard.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_Setup_ImportClipboard {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_Setup_ImportClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed!.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_Setup_ImportClipboard_Failure {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_Setup_ImportClipboard_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import success!.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_Setup_ImportClipboard_Success {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_Setup_ImportClipboard_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from file.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_Setup_ImportFile {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_Setup_ImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed!.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_Setup_ImportFile_Failure {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_Setup_ImportFile_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file ....
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_Setup_ImportFile_Select {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_Setup_ImportFile_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import success!.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_Setup_ImportFile_Success {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_Setup_ImportFile_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick from nearby NPC.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_Setup_PickNpc {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_Setup_PickNpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick from yourself.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_Setup_PickSelf {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_Setup_PickSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick from target.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_Setup_PickTarget {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_Setup_PickTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string ScenarioEditor_ActorData_Appearance_Title {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Appearance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the actor to edit here. You can define the actions for each actor individually..
        /// </summary>
        public static string ScenarioEditor_ActorData_Desc {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ScenarioEditor_ActorData_General_Input_Name {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_General_Input_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The npc does not output a name at any point. Its only use is to make it easier identifyable when editing the scenario..
        /// </summary>
        public static string ScenarioEditor_ActorData_General_Input_NameHint {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_General_Input_NameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create random name.
        /// </summary>
        public static string ScenarioEditor_ActorData_General_Input_NameRandom {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_General_Input_NameRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string ScenarioEditor_ActorData_General_Input_Position {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_General_Input_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to current location.
        /// </summary>
        public static string ScenarioEditor_ActorData_General_Input_PositionCurrent {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_General_Input_PositionCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roation.
        /// </summary>
        public static string ScenarioEditor_ActorData_General_Input_Rotation {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_General_Input_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to current rotation.
        /// </summary>
        public static string ScenarioEditor_ActorData_General_Input_RotationCurrent {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_General_Input_RotationCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string ScenarioEditor_ActorData_General_Title {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_General_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Actor.
        /// </summary>
        public static string ScenarioEditor_ActorData_Manage_AddActor {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Manage_AddActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Actor.
        /// </summary>
        public static string ScenarioEditor_ActorData_Manage_RemoveActor {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Manage_RemoveActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Actor:.
        /// </summary>
        public static string ScenarioEditor_ActorData_Manage_Select {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Manage_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Actor ....
        /// </summary>
        public static string ScenarioEditor_ActorData_Manage_SelectHint {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Manage_SelectHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Actor Data.
        /// </summary>
        public static string ScenarioEditor_ActorData_Title {
            get {
                return ResourceManager.GetString("ScenarioEditor_ActorData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ScenarioEditor_BaseData_Action_Apply {
            get {
                return ResourceManager.GetString("ScenarioEditor_BaseData_Action_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard &amp; Close.
        /// </summary>
        public static string ScenarioEditor_BaseData_Action_DiscardClose {
            get {
                return ResourceManager.GetString("ScenarioEditor_BaseData_Action_DiscardClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to clipboard.
        /// </summary>
        public static string ScenarioEditor_BaseData_Action_Export_Desc {
            get {
                return ResourceManager.GetString("ScenarioEditor_BaseData_Action_Export_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from clipboard.
        /// </summary>
        public static string ScenarioEditor_BaseData_Action_Import_Desc {
            get {
                return ResourceManager.GetString("ScenarioEditor_BaseData_Action_Import_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed!.
        /// </summary>
        public static string ScenarioEditor_BaseData_Action_Import_Failed {
            get {
                return ResourceManager.GetString("ScenarioEditor_BaseData_Action_Import_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import success!.
        /// </summary>
        public static string ScenarioEditor_BaseData_Action_Import_Success {
            get {
                return ResourceManager.GetString("ScenarioEditor_BaseData_Action_Import_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Close.
        /// </summary>
        public static string ScenarioEditor_BaseData_Action_SaveClose {
            get {
                return ResourceManager.GetString("ScenarioEditor_BaseData_Action_SaveClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the scenario information in this section. These are mostly meta data to identify the scenario on the user interface..
        /// </summary>
        public static string ScenarioEditor_BaseData_Desc {
            get {
                return ResourceManager.GetString("ScenarioEditor_BaseData_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string ScenarioEditor_BaseData_Input_Description {
            get {
                return ResourceManager.GetString("ScenarioEditor_BaseData_Input_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ScenarioEditor_BaseData_Input_Location {
            get {
                return ResourceManager.GetString("ScenarioEditor_BaseData_Input_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Current Location.
        /// </summary>
        public static string ScenarioEditor_BaseData_Input_LocationCurrent {
            get {
                return ResourceManager.GetString("ScenarioEditor_BaseData_Input_LocationCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looping:.
        /// </summary>
        public static string ScenarioEditor_BaseData_Input_Looping {
            get {
                return ResourceManager.GetString("ScenarioEditor_BaseData_Input_Looping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay between loops:.
        /// </summary>
        public static string ScenarioEditor_BaseData_Input_LoopingDelay {
            get {
                return ResourceManager.GetString("ScenarioEditor_BaseData_Input_LoopingDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string ScenarioEditor_BaseData_Input_Title {
            get {
                return ResourceManager.GetString("ScenarioEditor_BaseData_Input_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Meta Data.
        /// </summary>
        public static string ScenarioEditor_BaseData_Title {
            get {
                return ResourceManager.GetString("ScenarioEditor_BaseData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Location.
        /// </summary>
        public static string ScenarioEditor_FileInfo_Location {
            get {
                return ResourceManager.GetString("ScenarioEditor_FileInfo_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server {0} / Territory {1} / Division {2} / Ward {3} / Plot {4}.
        /// </summary>
        public static string ScenarioEditor_FileInfo_LocationDetails {
            get {
                return ResourceManager.GetString("ScenarioEditor_FileInfo_LocationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario File Name.
        /// </summary>
        public static string ScenarioEditor_FileInfo_Name {
            get {
                return ResourceManager.GetString("ScenarioEditor_FileInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not yet saved.
        /// </summary>
        public static string ScenarioEditor_FileInfo_Unsaved {
            get {
                return ResourceManager.GetString("ScenarioEditor_FileInfo_Unsaved", resourceCulture);
            }
        }
    }
}
